Repository pglombardo/PasswordPusher, pull requests merged in 2023-08, with the labels that each got.

#1308 Fix URL push 1-click option
  app/controllers/urls_controller.rb
Labels: bug moderate

#1310 Updated robots.txt
  public/robots.txt
Labels: enhancement

#1311 Improved Feedback Form
  Gemfile
  Gemfile.lock
  app/controllers/feedbacks_controller.rb
  app/models/feedback.rb
  app/views/feedbacks/create.html.erb
  app/views/feedbacks/new.html.erb
Labels: enhancement

#1203 Change to use docker metadata action for tags
  .github/workflows/docker-containers.yml
Labels: enhancement

#1318 Bundler update
  Gemfile.lock
Labels: dependencies

#1336 Improve Override URL: Add host to allowed domains
  app/controllers/file_pushes_controller.rb
  config/environments/development.rb
  config/environments/private.rb
  config/environments/production.rb
Labels: bug minor

#1348 Add Array support to PWP__ALLOWED_HOSTS
  config/defaults/settings.yml
  config/environments/development.rb
  config/environments/private.rb
  config/environments/production.rb
  config/settings.yml
Labels: enhancement

#1345 Throttling: Increase default thresholds
  config/defaults/settings.yml
  config/settings.yml
Labels: enhancement

#1367 Better container precompile boot message
  containers/docker/pwpush-ephemeral/entrypoint.sh
  containers/docker/pwpush-mysql/entrypoint.sh
  containers/docker/pwpush-postgres/entrypoint.sh
Labels: enhancement

#1309 Update bundled themes to latest versions
  app/assets/stylesheets/themes/cerulean.css
  app/assets/stylesheets/themes/cosmo.css
  app/assets/stylesheets/themes/cyborg.css
  app/assets/stylesheets/themes/darkly.css
  app/assets/stylesheets/themes/flatly.css
  app/assets/stylesheets/themes/journal.css
  app/assets/stylesheets/themes/litera.css
  app/assets/stylesheets/themes/lumen.css
  app/assets/stylesheets/themes/lux.css
  app/assets/stylesheets/themes/materia.css
  app/assets/stylesheets/themes/minty.css
  app/assets/stylesheets/themes/morph.css
  app/assets/stylesheets/themes/pulse.css
  app/assets/stylesheets/themes/quartz.css
  app/assets/stylesheets/themes/sandstone.css
  app/assets/stylesheets/themes/simplex.css
  app/assets/stylesheets/themes/sketchy.css
  app/assets/stylesheets/themes/slate.css
  app/assets/stylesheets/themes/solar.css
  app/assets/stylesheets/themes/spacelab.css
  app/assets/stylesheets/themes/superhero.css
  app/assets/stylesheets/themes/united.css
  app/assets/stylesheets/themes/vapor.css
  app/assets/stylesheets/themes/yeti.css
  app/assets/stylesheets/themes/zephyr.css
  lib/tasks/pwpush.rake
Labels: enhancement

#1376 Fix: Dark theme regression with updated Bootstrap
  Gemfile
  Gemfile.lock
Labels: bug moderate

#1391 Fix: Increase default throttle limits
  config/defaults/settings.yml
  config/settings.yml
Labels: enhancement
