Repository pglombardo/PasswordPusher, pull requests merged in 2023-03, with the labels that each got.

#912 Locale: Add LC environment variables
  containers/docker/pwpush-ephemeral/Dockerfile
  containers/docker/pwpush-mysql/Dockerfile
  containers/docker/pwpush-postgres/Dockerfile
Labels: bug moderate

#907 feat: adds basic helm chart with deployment and service
  README.md
  containers/helm/.helmignore
  containers/helm/Chart.yaml
  containers/helm/README.md
  containers/helm/templates/_helpers.tpl
  containers/helm/templates/deployment.yaml
  containers/helm/templates/service.yaml
  containers/helm/values.yaml
Labels: enhancement

#824 Add Support for Built in Themes (26 of them)
  Configuration.md
  Themes.md
  app/assets/stylesheets/application.scss.erb
  app/assets/stylesheets/custom.css
  app/assets/stylesheets/themes/BOOTSWATCH_LICENSE
  app/assets/stylesheets/themes/cerulean.css
  app/assets/stylesheets/themes/cosmo.css
  app/assets/stylesheets/themes/cyborg.css
  app/assets/stylesheets/themes/darkly.css
  app/assets/stylesheets/themes/default.css
  app/assets/stylesheets/themes/flatly.css
  app/assets/stylesheets/themes/journal.css
  app/assets/stylesheets/themes/litera.css
  app/assets/stylesheets/themes/lumen.css
  app/assets/stylesheets/themes/lux.css
  app/assets/stylesheets/themes/materia.css
  app/assets/stylesheets/themes/minty.css
  app/assets/stylesheets/themes/morph.css
  app/assets/stylesheets/themes/pulse.css
  app/assets/stylesheets/themes/quartz.css
  app/assets/stylesheets/themes/sandstone.css
  app/assets/stylesheets/themes/simplex.css
  app/assets/stylesheets/themes/sketchy.css
  app/assets/stylesheets/themes/slate.css
  app/assets/stylesheets/themes/solar.css
  app/assets/stylesheets/themes/spacelab.css
  app/assets/stylesheets/themes/superhero.css
  app/assets/stylesheets/themes/united.css
  app/assets/stylesheets/themes/vapor.css
  app/assets/stylesheets/themes/varpor.css
  app/assets/stylesheets/themes/yeti.css
  app/assets/stylesheets/themes/zephyr.css
  config/defaults/settings.yml
  config/settings.yml
  lib/tasks/pwpush.rake
Labels: feature request, enhancement

#932 Custom CSS: Use different import style for proper ordering
  app/assets/stylesheets/application.scss.erb
Labels: bug minor

#933 URLs: Fix max value setting
  app/views/urls/new.html.erb
Labels: bug minor

#971 Files: Fix Javascript Upload
  app/assets/javascripts/application.js
  app/javascript/controllers/index.js
  app/views/file_pushes/new.html.erb
  config/environments/development.rb
  lib/tasks/pwpush.rake
Labels: bug moderate
