Repository pglombardo/PasswordPusher, pull requests merged in 2023-10, with the labels that each got.

#1489 sqlite3: force_ruby_platform & drop Ruby 3.1 from tests
  .github/workflows/ruby-tests.yml
  Gemfile
  Gemfile.lock
Labels: bug moderate

#1512 Update Robots.txt and rake task generator
  lib/tasks/pwpush.rake
  public/robots.txt
Labels: enhancement

#1513 Fix copy to clipboard buttons on Generate Key page
  app/views/pages/generate_key.html.erb
Labels: bug minor

#1514 More Robots.txt updates
  lib/tasks/pwpush.rake
  public/robots.txt
Labels: enhancement

#1509 feat: add support for showing a disclaimer
  app/views/shared/_footer.html.erb
  config/defaults/settings.yml
  config/settings.yml
Labels: feature request, enhancement

#1521 docs: update disclaimer examples
  Configuration.md
  containers/examples/pwpush-and-nginx/env-file
Labels: enhancement

#1525 Latest Language Strings
  config/locales/.translation_io
  config/locales/gettext/app.pot
  config/locales/gettext/ca/LC_MESSAGES/app.mo
  config/locales/gettext/ca/app.po
  config/locales/gettext/cs/LC_MESSAGES/app.mo
  config/locales/gettext/cs/app.po
  config/locales/gettext/da/LC_MESSAGES/app.mo
  config/locales/gettext/da/app.po
  config/locales/gettext/de/LC_MESSAGES/app.mo
  config/locales/gettext/de/app.po
  config/locales/gettext/en/LC_MESSAGES/app.mo
  config/locales/gettext/en/app.po
  config/locales/gettext/es/LC_MESSAGES/app.mo
  config/locales/gettext/es/app.po
  config/locales/gettext/fi/LC_MESSAGES/app.mo
  config/locales/gettext/fi/app.po
  config/locales/gettext/fr/LC_MESSAGES/app.mo
  config/locales/gettext/fr/app.po
  config/locales/gettext/hi/LC_MESSAGES/app.mo
  config/locales/gettext/hi/app.po
  config/locales/gettext/hu/LC_MESSAGES/app.mo
  config/locales/gettext/hu/app.po
  config/locales/gettext/id/LC_MESSAGES/app.mo
  config/locales/gettext/id/app.po
  config/locales/gettext/is/LC_MESSAGES/app.mo
  config/locales/gettext/is/app.po
  config/locales/gettext/it/LC_MESSAGES/app.mo
  config/locales/gettext/it/app.po
  config/locales/gettext/ja/LC_MESSAGES/app.mo
  config/locales/gettext/ja/app.po
  config/locales/gettext/ko/LC_MESSAGES/app.mo
  config/locales/gettext/ko/app.po
  config/locales/gettext/lv/LC_MESSAGES/app.mo
  config/locales/gettext/lv/app.po
  config/locales/gettext/nl/LC_MESSAGES/app.mo
  config/locales/gettext/nl/app.po
  config/locales/gettext/no/LC_MESSAGES/app.mo
  config/locales/gettext/no/app.po
  config/locales/gettext/pl/LC_MESSAGES/app.mo
  config/locales/gettext/pl/app.po
  config/locales/gettext/pt_BR/LC_MESSAGES/app.mo
  config/locales/gettext/pt_BR/app.po
  config/locales/gettext/pt_PT/LC_MESSAGES/app.mo
  config/locales/gettext/pt_PT/app.po
  config/locales/gettext/ro/LC_MESSAGES/app.mo
  config/locales/gettext/ro/app.po
  config/locales/gettext/ru/LC_MESSAGES/app.mo
  config/locales/gettext/ru/app.po
  config/locales/gettext/sr/LC_MESSAGES/app.mo
  config/locales/gettext/sr/app.po
  config/locales/gettext/sv/LC_MESSAGES/app.mo
  config/locales/gettext/sv/app.po
  config/locales/gettext/th/LC_MESSAGES/app.mo
  config/locales/gettext/th/app.po
  config/locales/gettext/uk/LC_MESSAGES/app.mo
  config/locales/gettext/uk/app.po
  config/locales/gettext/ur/LC_MESSAGES/app.mo
  config/locales/gettext/ur/app.po
  config/locales/gettext/zh_CN/LC_MESSAGES/app.mo
  config/locales/gettext/zh_CN/app.po
Labels: enhancement

#1510 refactor(dockerfile): move layers around for speed improvement
  Gemfile.lock
  containers/docker/pwpush/Dockerfile
Labels: enhancement

#1526 Update references to point to universal container image
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  Configuration.md
  app/views/pages/faq.html.erb
  containers/docker/pwpush/Dockerfile
Labels: documentation

#1546 Feedback: Better Spam Checks
  .rubocop.yml
  app/controllers/feedbacks_controller.rb
  app/models/feedback.rb
  app/views/feedbacks/new.html.erb
  test/models/feedback_test.rb
Labels: enhancement

#1553 Feedback Spam: A few more for the check
  app/models/feedback.rb
Labels: enhancement

#1554 URL Pushes: Workaround for CORS bug in redirect
  app/controllers/urls_controller.rb
  test/integration/url/url_passphrase_test.rb
Labels: bug moderate

#1561 Revise zh-CN label in application language menu
  config/defaults/settings.yml
  config/settings.yml
Labels: bug minor

#1568 Add Support for IAM and Workload Identity on GCS
  config/defaults/settings.yml
  config/settings.yml
  config/storage.yml
Labels: enhancement
