Repository pglombardo/PasswordPusher, pull requests merged in 2023-12, with the labels that each got.

#1555 DOCKER: removed deprecated docker containers and references
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/dependabot.yml
  .github/workflows/docker-containers.yml
  Configuration.md
  README.md
  containers/docker/Dockerfile
  containers/docker/README.md
  containers/docker/docker-compose-ephemeral.yml
  containers/docker/docker-compose-mariadb.yml
  containers/docker/docker-compose-mysql.yml
  containers/docker/docker-compose-postgres.yml
  containers/docker/entrypoint.sh
  containers/docker/pwpush-ephemeral/Dockerfile
  containers/docker/pwpush-ephemeral/docker-compose.yml
  containers/docker/pwpush-mysql/Dockerfile
  containers/docker/pwpush-mysql/docker-compose-mariadb.yml
  containers/docker/pwpush-postgres/Dockerfile
  containers/docker/pwpush-postgres/docker-compose.yml
  containers/docker/pwpush/docker-compose-ephemeral.yml
Labels: dependencies

#1731 Update flag-icons to 7.1.0
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/bare.html.erb
  app/views/layouts/login.html.erb
  app/views/layouts/naked.html.erb
Labels: dependencies

#1707 Migrate to Rails 7.1 Settings
  Configuration.md
  config/initializers/new_framework_defaults_7_1.rb
  config/initializers/secret_token.rb
Labels: dependencies

#1736 Remove Profiler
  Gemfile
  Gemfile.lock
Labels: dependencies

#1747 Framework: Set default key base
  .gitignore
  .pre-commit-config.yaml
  config/credentials.yml.enc
  config/environments/production.rb
Labels: bug minor

#1748 Move key base to Dockerfile
  config/credentials.yml.enc
  containers/docker/Dockerfile
Labels: bug minor

#1752 Remove MiniProfiler call
  app/controllers/application_controller.rb
Labels: bug critical

#1753 Small Memory Improvement
  Gemfile
  Gemfile.lock
Labels: enhancement

#1754 Add SECRET_KEY_BASE to Dockerfile
  containers/docker/Dockerfile
Labels: bug moderate
