Repository pglombardo/PasswordPusher, pull requests merged in 2023-09, with the labels that each got.

#1435 faq typo fix
  app/views/pages/faq.html.erb
Labels: documentation

#1461 Revert ":arrow_up: Bump bootstrap from 5.2.3 to 5.3.1"
  Gemfile
  Gemfile.lock
Labels: bug minor

#1483 Bundle and Yarn updates
  Gemfile
  Gemfile.lock
  config/initializers/route_translator.rb
  yarn.lock
Labels: dependencies
