Repository pglombardo/PasswordPusher, pull requests merged in 2023-01, with the labels that each got.

#671 Fix ActiveRecord JS and Better Asset Management
  app/assets/config/manifest.js
  app/javascript/application.js
Labels: bug moderate

#685 Fix: Copy Payload Has Spaces
  app/views/file_pushes/show.html.erb
  app/views/passwords/show.html.erb
Labels: bug minor

#687 Fix: Registration + Turbo Streams
  config/initializers/devise.rb
Labels: bug critical

#561 Run container processes with a dedicated user
  containers/docker/pwpush-ephemeral/Dockerfile
  containers/docker/pwpush-mysql/Dockerfile
  containers/docker/pwpush-postgres/Dockerfile
Labels: enhancement

#717 Fix: No Registration links when Disable Signups is set
  app/views/file_pushes/new_anonymous.html.erb
  app/views/urls/new_anonymous.html.erb
  test/integration/create_account_test.rb
  test/integration/file_push/file_push_anonymous_access.rb
  test/integration/url/url_anonymous_access.rb
Labels: bug minor

#714 Docker: Switch to multistage build to reduce container size
  .dockerignore
  containers/docker/pwpush-ephemeral/Dockerfile
  containers/docker/pwpush-mysql/Dockerfile
  containers/docker/pwpush-postgres/Dockerfile
Labels: enhancement, docker

#774 Docker: Don't Precompile Assets by Default
  config/defaults/settings.yml
  config/settings.yml
  containers/docker/pwpush-ephemeral/entrypoint.sh
  containers/docker/pwpush-mysql/entrypoint.sh
  containers/docker/pwpush-postgres/entrypoint.sh
Labels: enhancement
