Repository pglombardo/PasswordPusher, pull requests merged in 2023-02, with the labels that each got.

#785 Add newsletter link (pwpush.com only)
  app/views/pages/about.html.erb
  app/views/shared/_newsletter_sign_up.html.erb
Labels: enhancement

#786 Latest language strings
  config/locales/.translation_io
  config/locales/gettext/app.pot
  config/locales/gettext/ca/LC_MESSAGES/app.mo
  config/locales/gettext/ca/app.po
  config/locales/gettext/cs/LC_MESSAGES/app.mo
  config/locales/gettext/cs/app.po
  config/locales/gettext/da/LC_MESSAGES/app.mo
  config/locales/gettext/da/app.po
  config/locales/gettext/de/LC_MESSAGES/app.mo
  config/locales/gettext/de/app.po
  config/locales/gettext/en/LC_MESSAGES/app.mo
  config/locales/gettext/en/app.po
  config/locales/gettext/es/LC_MESSAGES/app.mo
  config/locales/gettext/es/app.po
  config/locales/gettext/fi/LC_MESSAGES/app.mo
  config/locales/gettext/fi/app.po
  config/locales/gettext/fr/LC_MESSAGES/app.mo
  config/locales/gettext/fr/app.po
  config/locales/gettext/hu/LC_MESSAGES/app.mo
  config/locales/gettext/hu/app.po
  config/locales/gettext/it/LC_MESSAGES/app.mo
  config/locales/gettext/it/app.po
  config/locales/gettext/lv/LC_MESSAGES/app.mo
  config/locales/gettext/lv/app.po
  config/locales/gettext/nl/LC_MESSAGES/app.mo
  config/locales/gettext/nl/app.po
  config/locales/gettext/no/LC_MESSAGES/app.mo
  config/locales/gettext/no/app.po
  config/locales/gettext/pl/LC_MESSAGES/app.mo
  config/locales/gettext/pl/app.po
  config/locales/gettext/pt_BR/LC_MESSAGES/app.mo
  config/locales/gettext/pt_BR/app.po
  config/locales/gettext/pt_PT/LC_MESSAGES/app.mo
  config/locales/gettext/pt_PT/app.po
  config/locales/gettext/sr/LC_MESSAGES/app.mo
  config/locales/gettext/sr/app.po
  config/locales/gettext/sv/LC_MESSAGES/app.mo
  config/locales/gettext/sv/app.po
  config/locales/gettext/zh_CN/LC_MESSAGES/app.mo
  config/locales/gettext/zh_CN/app.po
Labels: enhancement

#792 Latest language strings
  config/locales/.translation_io
  config/locales/gettext/app.pot
  config/locales/gettext/ca/LC_MESSAGES/app.mo
  config/locales/gettext/ca/app.po
  config/locales/gettext/cs/LC_MESSAGES/app.mo
  config/locales/gettext/cs/app.po
  config/locales/gettext/da/LC_MESSAGES/app.mo
  config/locales/gettext/da/app.po
  config/locales/gettext/de/LC_MESSAGES/app.mo
  config/locales/gettext/de/app.po
  config/locales/gettext/en/LC_MESSAGES/app.mo
  config/locales/gettext/en/app.po
  config/locales/gettext/es/LC_MESSAGES/app.mo
  config/locales/gettext/es/app.po
  config/locales/gettext/fi/LC_MESSAGES/app.mo
  config/locales/gettext/fi/app.po
  config/locales/gettext/fr/LC_MESSAGES/app.mo
  config/locales/gettext/fr/app.po
  config/locales/gettext/hu/LC_MESSAGES/app.mo
  config/locales/gettext/hu/app.po
  config/locales/gettext/it/LC_MESSAGES/app.mo
  config/locales/gettext/it/app.po
  config/locales/gettext/lv/LC_MESSAGES/app.mo
  config/locales/gettext/lv/app.po
  config/locales/gettext/nl/LC_MESSAGES/app.mo
  config/locales/gettext/nl/app.po
  config/locales/gettext/no/LC_MESSAGES/app.mo
  config/locales/gettext/no/app.po
  config/locales/gettext/pl/LC_MESSAGES/app.mo
  config/locales/gettext/pl/app.po
  config/locales/gettext/pt_BR/LC_MESSAGES/app.mo
  config/locales/gettext/pt_BR/app.po
  config/locales/gettext/pt_PT/LC_MESSAGES/app.mo
  config/locales/gettext/pt_PT/app.po
  config/locales/gettext/sr/LC_MESSAGES/app.mo
  config/locales/gettext/sr/app.po
  config/locales/gettext/sv/LC_MESSAGES/app.mo
  config/locales/gettext/sv/app.po
  config/locales/gettext/zh_CN/LC_MESSAGES/app.mo
  config/locales/gettext/zh_CN/app.po
  config/locales/translation.pt-PT.yml
Labels: enhancement

#803 Latest language strings
  config/locales/.translation_io
  config/locales/gettext/app.pot
  config/locales/gettext/ca/LC_MESSAGES/app.mo
  config/locales/gettext/ca/app.po
  config/locales/gettext/cs/LC_MESSAGES/app.mo
  config/locales/gettext/cs/app.po
  config/locales/gettext/da/LC_MESSAGES/app.mo
  config/locales/gettext/da/app.po
  config/locales/gettext/de/LC_MESSAGES/app.mo
  config/locales/gettext/de/app.po
  config/locales/gettext/en/LC_MESSAGES/app.mo
  config/locales/gettext/en/app.po
  config/locales/gettext/es/LC_MESSAGES/app.mo
  config/locales/gettext/es/app.po
  config/locales/gettext/fi/LC_MESSAGES/app.mo
  config/locales/gettext/fi/app.po
  config/locales/gettext/fr/LC_MESSAGES/app.mo
  config/locales/gettext/fr/app.po
  config/locales/gettext/hu/LC_MESSAGES/app.mo
  config/locales/gettext/hu/app.po
  config/locales/gettext/it/LC_MESSAGES/app.mo
  config/locales/gettext/it/app.po
  config/locales/gettext/lv/LC_MESSAGES/app.mo
  config/locales/gettext/lv/app.po
  config/locales/gettext/nl/LC_MESSAGES/app.mo
  config/locales/gettext/nl/app.po
  config/locales/gettext/no/LC_MESSAGES/app.mo
  config/locales/gettext/no/app.po
  config/locales/gettext/pl/LC_MESSAGES/app.mo
  config/locales/gettext/pl/app.po
  config/locales/gettext/pt_BR/LC_MESSAGES/app.mo
  config/locales/gettext/pt_BR/app.po
  config/locales/gettext/pt_PT/LC_MESSAGES/app.mo
  config/locales/gettext/pt_PT/app.po
  config/locales/gettext/sr/LC_MESSAGES/app.mo
  config/locales/gettext/sr/app.po
  config/locales/gettext/sv/LC_MESSAGES/app.mo
  config/locales/gettext/sv/app.po
  config/locales/gettext/zh_CN/LC_MESSAGES/app.mo
  config/locales/gettext/zh_CN/app.po
Labels: enhancement

#806 Updated copyright dates
  LICENSE
  config/initializers/apipie.rb
Labels: enhancement

#811 File Push: Add data safety
  app/controllers/file_pushes_controller.rb
Labels: bug minor

#810 Migrate to esbuild for JS packaging
  app/assets/config/manifest.js
  app/assets/javascripts/application.js
  app/javascript/application.js
  app/javascript/controllers/index.js
  app/javascript/controllers/passwords_controller.js
  app/views/layouts/application.html.erb
  app/views/layouts/bare.html.erb
  app/views/layouts/login.html.erb
  app/views/layouts/naked.html.erb
  config/importmap.rb
  package-lock.json
  package.json
  vendor/javascript/.keep
  vendor/javascript/@hotwired--stimulus.js
  vendor/javascript/@hotwired--turbo-rails.js
  vendor/javascript/@hotwired--turbo.js
  vendor/javascript/@popperjs--core.js
  vendor/javascript/@rails--actioncable--src.js
  vendor/javascript/@rails--activestorage.js
  vendor/javascript/clipboard.js
  vendor/javascript/js-cookie.js
  vendor/javascript/omgopass--random.js.js
  vendor/javascript/omgopass.js
Labels: javascript

#815 Docker: fix broken docker arm builds
  Gemfile
  Gemfile.lock
  containers/docker/pwpush-ephemeral/Dockerfile
  containers/docker/pwpush-mysql/Dockerfile
  containers/docker/pwpush-postgres/Dockerfile
Labels: bug moderate

#822 Add Example Docker env-file
  containers/docker/pwpush-docker-env-file
  containers/docker/pwpush-ephemeral/docker-compose.yml
  containers/docker/pwpush-mysql/docker-compose.yml
  containers/docker/pwpush-postgres/docker-compose.yml
Labels: documentation

#837 Default Locale: Use custom handler to force default fallback
  app/controllers/application_controller.rb
Labels: bug minor

#845 Settings: Add Option to Disable Blur Effect on Payload Delivery
  Configuration.md
  app/controllers/passwords_controller.rb
  app/views/passwords/show.html.erb
  config/defaults/settings.yml
  config/settings.yml
Labels: feature request
