Repository pglombardo/PasswordPusher, pull requests merged in 2024-12, with the labels that each got.

#2821 fix database service names in docker-compose-xx.yml
  containers/docker/docker-compose-mariadb.yml
  containers/docker/docker-compose-mysql.yml
Labels: bug moderate

#2854 Preliminary: Set rel="no-prefetch" to block browser pre-fetch
  app/views/file_pushes/preliminary.html.erb
  app/views/passwords/preliminary.html.erb
  app/views/urls/preliminary.html.erb
Labels: bug minor

#2877 Special fix for Mariadb
  app/controllers/passwords_controller.rb
Labels: bug minor

#2878 New Cloudflare Setting: Optionally fetch CF IPs on container boot.
  config/defaults/settings.yml
  config/initializers/cloudflare_proxy.rb
  config/settings.yml
Labels: feature request

#2916 Fix: Custom theme setup on container boot
  containers/docker/Dockerfile
  containers/docker/docker-compose-ephemeral.yml
  containers/docker/docker-compose-mariadb.yml
  containers/docker/docker-compose-mysql.yml
  containers/docker/docker-compose-postgres.yml
  containers/docker/entrypoint.sh
Labels: bug moderate

#2921 Fix: Downcase theme selection
  set_theme.js
Labels: bug minor

#2942 Cyborg Theme: Upstream Bootswatch Fix
  app/assets/stylesheets/themes/cyborg.css
Labels: bug minor
