Repository pglombardo/PasswordPusher, pull requests merged in 2024-06, with the labels that each got.

#2192 Launch Password Pusher with Let's Encrypt SSL/TLS Certificates
  README.md
  containers/docker/all-in-one/Caddyfile
  containers/docker/all-in-one/README.md
  containers/docker/all-in-one/docker-compose-pwpush.yml
Labels: enhancement, documentation, docker, self-hosted

#2201 Caddy: Add Secure Cookies Policy
  containers/docker/all-in-one/Caddyfile
Labels: documentation

#2252 Adjust helm chart to runAsNonRoot
  containers/helm/templates/deployment.yaml
Labels: enhancement

#2261 Add Admin Route Protection
  config/routes.rb
  test/integration/admin_dashboard_test.rb
Labels: security

#2285 1-click: Immediately show expired message if push is expired
  app/controllers/file_pushes_controller.rb
  app/controllers/passwords_controller.rb
  app/controllers/urls_controller.rb
  test/integration/file_push/file_push_deletion_test.rb
  test/integration/password/password_deletion_test.rb
Labels: feature request
