Repository pglombardo/PasswordPusher, pull requests merged in 2025-05, with the labels that each got.

#3339 Add a .ruby-version file
  .ruby-version
Labels: enhancement

#3338 Themes: Remove selected.css; generated on boot
  app/assets/stylesheets/themes/selected.css
Labels: enhancement

#3343 Update ruby version bundling gems
  .github/workflows/brakeman.yml
  .github/workflows/ruby-tests.yml
  Gemfile
  Gemfile.lock
Labels: dependencies

#3351 Add `name` to pushes
  app/controllers/api/v1/file_pushes_controller.rb
  app/controllers/api/v1/passwords_controller.rb
  app/controllers/api/v1/urls_controller.rb
  app/controllers/file_pushes_controller.rb
  app/controllers/passwords_controller.rb
  app/controllers/urls_controller.rb
  app/models/file_push.rb
  app/models/password.rb
  app/models/url.rb
  app/views/file_pushes/active.html.erb
  app/views/file_pushes/new.html.erb
  app/views/passwords/active.html.erb
  app/views/passwords/new.html.erb
  app/views/urls/active.html.erb
  app/views/urls/new.html.erb
  config/locales/pwpx.en.yml
  db/migrate/20250513074136_add_name_to_models.rb
  db/schema.rb
  test/integration/file_push/file_push_active_test.rb
  test/integration/file_push/file_push_json_creation_test.rb
  test/integration/password/password_active_test.rb
  test/integration/password/password_json_creation_test.rb
  test/integration/url/url_active_test.rb
  test/integration/url/url_json_creation_test.rb
  test/models/file_push_test.rb
  test/models/password_test.rb
  test/models/url_test.rb
  test/unit/password_unit_test.rb
Labels: feature request

#3353 Add a "Save" button into two tabs
  .github/workflows/ruby-tests.yml
  app/javascript/controllers/knobs_controller.js
  app/views/file_pushes/new.html.erb
  app/views/passwords/new.html.erb
  app/views/urls/new.html.erb
  test/application_system_test_case.rb
  test/system/file_push_cookies_test.rb
  test/system/file_pushes_test.rb
  test/system/password_cookies_test.rb
  test/system/url_cookies_test.rb
  test/system/urls_test.rb
Labels: feature request

#3358 Remove unused text columns from urls and file_pushes tables
  db/migrate/20250515110051_remove_text_from_urls_and_file_pushes.rb
  db/schema.rb
Labels: bug minor

#3369 feat: Added minio support for S3 storage
  config/defaults/settings.yml
  config/settings.yml
  config/storage.yml
Labels: feature request
